import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./_Components/Navbar/Navbar";
import Footer from "./_Components/Footer/page";
import { Providers } from "./providers/heroProvider";
import BgPatrens from "./_Components/bgPatrens/bgPatrens";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Euphoria",
  description: "Generated by create next app",
};

//children typing
interface RootLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          <div className="container py-4">
            <BgPatrens />
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
